name: Run PR Checks

on:
  pull_request:
    branches:
      - develop # Branch to run checks on

jobs:
  check_release_notes:
    runs-on: ubuntu-latest
    name: Verify RELEASE_NOTES.md has been updated
    steps:
      - name: Verify RELEASE_NOTES.md updated
        uses: takanuva15/verify-file-updated@v1
        with:
          filename_to_check: RELEASE_NOTES.md # Check the RELEASE_NOTES.md for change
          excused_label: "no release notes check" # Optional: add this label to PRs to skip the check
